/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as FirstRouteIndexRouteImport } from './routes/first-route/index'
import { Route as TestChildTestRouteImport } from './routes/test/child-test'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as authAuth_layoutRouteImport } from './routes/(auth)/_auth_layout'
import { Route as FirstRouteFirstRouteChildIndexRouteImport } from './routes/first-route/first-route-child/index'
import { Route as FirstRouteFirstRouteChildNestedChildRouteImport } from './routes/first-route/first-route-child/nested-child'
import { Route as authAuth_layoutPrefixedRouteSignupRouteImport } from './routes/(auth)/_auth_layout/prefixed-route/signup'
import { Route as authAuth_layoutPrefixedRouteLoginRouteImport } from './routes/(auth)/_auth_layout/prefixed-route/login'

const IndexLazyRouteImport = createFileRoute('/')()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRouteIndexRoute = FirstRouteIndexRouteImport.update({
  id: '/first-route/',
  path: '/first-route/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChildTestRoute = TestChildTestRouteImport.update({
  id: '/test/child-test',
  path: '/test/child-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const authAuth_layoutRoute = authAuth_layoutRouteImport.update({
  id: '/(auth)/_auth_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRouteFirstRouteChildIndexRoute =
  FirstRouteFirstRouteChildIndexRouteImport.update({
    id: '/first-route/first-route-child/',
    path: '/first-route/first-route-child/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FirstRouteFirstRouteChildNestedChildRoute =
  FirstRouteFirstRouteChildNestedChildRouteImport.update({
    id: '/first-route/first-route-child/nested-child',
    path: '/first-route/first-route-child/nested-child',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuth_layoutPrefixedRouteSignupRoute =
  authAuth_layoutPrefixedRouteSignupRouteImport.update({
    id: '/prefixed-route/signup',
    path: '/prefixed-route/signup',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutPrefixedRouteLoginRoute =
  authAuth_layoutPrefixedRouteLoginRouteImport.update({
    id: '/prefixed-route/login',
    path: '/prefixed-route/login',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/home': typeof LayoutHomeRoute
  '/test/child-test': typeof TestChildTestRoute
  '/first-route': typeof FirstRouteIndexRoute
  '/test': typeof TestIndexRoute
  '/first-route/first-route-child/nested-child': typeof FirstRouteFirstRouteChildNestedChildRoute
  '/first-route/first-route-child': typeof FirstRouteFirstRouteChildIndexRoute
  '/prefixed-route/login': typeof authAuth_layoutPrefixedRouteLoginRoute
  '/prefixed-route/signup': typeof authAuth_layoutPrefixedRouteSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/home': typeof LayoutHomeRoute
  '/test/child-test': typeof TestChildTestRoute
  '/first-route': typeof FirstRouteIndexRoute
  '/test': typeof TestIndexRoute
  '/first-route/first-route-child/nested-child': typeof FirstRouteFirstRouteChildNestedChildRoute
  '/first-route/first-route-child': typeof FirstRouteFirstRouteChildIndexRoute
  '/prefixed-route/login': typeof authAuth_layoutPrefixedRouteLoginRoute
  '/prefixed-route/signup': typeof authAuth_layoutPrefixedRouteSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/(auth)/_auth_layout': typeof authAuth_layoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/test/child-test': typeof TestChildTestRoute
  '/first-route/': typeof FirstRouteIndexRoute
  '/test/': typeof TestIndexRoute
  '/first-route/first-route-child/nested-child': typeof FirstRouteFirstRouteChildNestedChildRoute
  '/first-route/first-route-child/': typeof FirstRouteFirstRouteChildIndexRoute
  '/(auth)/_auth_layout/prefixed-route/login': typeof authAuth_layoutPrefixedRouteLoginRoute
  '/(auth)/_auth_layout/prefixed-route/signup': typeof authAuth_layoutPrefixedRouteSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/test/child-test'
    | '/first-route'
    | '/test'
    | '/first-route/first-route-child/nested-child'
    | '/first-route/first-route-child'
    | '/prefixed-route/login'
    | '/prefixed-route/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home'
    | '/test/child-test'
    | '/first-route'
    | '/test'
    | '/first-route/first-route-child/nested-child'
    | '/first-route/first-route-child'
    | '/prefixed-route/login'
    | '/prefixed-route/signup'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/(auth)/_auth_layout'
    | '/_layout/about'
    | '/_layout/contact'
    | '/_layout/home'
    | '/test/child-test'
    | '/first-route/'
    | '/test/'
    | '/first-route/first-route-child/nested-child'
    | '/first-route/first-route-child/'
    | '/(auth)/_auth_layout/prefixed-route/login'
    | '/(auth)/_auth_layout/prefixed-route/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  authAuth_layoutRoute: typeof authAuth_layoutRouteWithChildren
  TestChildTestRoute: typeof TestChildTestRoute
  FirstRouteIndexRoute: typeof FirstRouteIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  FirstRouteFirstRouteChildNestedChildRoute: typeof FirstRouteFirstRouteChildNestedChildRoute
  FirstRouteFirstRouteChildIndexRoute: typeof FirstRouteFirstRouteChildIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-route/': {
      id: '/first-route/'
      path: '/first-route'
      fullPath: '/first-route'
      preLoaderRoute: typeof FirstRouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/child-test': {
      id: '/test/child-test'
      path: '/test/child-test'
      fullPath: '/test/child-test'
      preLoaderRoute: typeof TestChildTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/(auth)/_auth_layout': {
      id: '/(auth)/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-route/first-route-child/': {
      id: '/first-route/first-route-child/'
      path: '/first-route/first-route-child'
      fullPath: '/first-route/first-route-child'
      preLoaderRoute: typeof FirstRouteFirstRouteChildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-route/first-route-child/nested-child': {
      id: '/first-route/first-route-child/nested-child'
      path: '/first-route/first-route-child/nested-child'
      fullPath: '/first-route/first-route-child/nested-child'
      preLoaderRoute: typeof FirstRouteFirstRouteChildNestedChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth_layout/prefixed-route/signup': {
      id: '/(auth)/_auth_layout/prefixed-route/signup'
      path: '/prefixed-route/signup'
      fullPath: '/prefixed-route/signup'
      preLoaderRoute: typeof authAuth_layoutPrefixedRouteSignupRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/prefixed-route/login': {
      id: '/(auth)/_auth_layout/prefixed-route/login'
      path: '/prefixed-route/login'
      fullPath: '/prefixed-route/login'
      preLoaderRoute: typeof authAuth_layoutPrefixedRouteLoginRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutHomeRoute: LayoutHomeRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface authAuth_layoutRouteChildren {
  authAuth_layoutPrefixedRouteLoginRoute: typeof authAuth_layoutPrefixedRouteLoginRoute
  authAuth_layoutPrefixedRouteSignupRoute: typeof authAuth_layoutPrefixedRouteSignupRoute
}

const authAuth_layoutRouteChildren: authAuth_layoutRouteChildren = {
  authAuth_layoutPrefixedRouteLoginRoute:
    authAuth_layoutPrefixedRouteLoginRoute,
  authAuth_layoutPrefixedRouteSignupRoute:
    authAuth_layoutPrefixedRouteSignupRoute,
}

const authAuth_layoutRouteWithChildren = authAuth_layoutRoute._addFileChildren(
  authAuth_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LayoutRoute: LayoutRouteWithChildren,
  authAuth_layoutRoute: authAuth_layoutRouteWithChildren,
  TestChildTestRoute: TestChildTestRoute,
  FirstRouteIndexRoute: FirstRouteIndexRoute,
  TestIndexRoute: TestIndexRoute,
  FirstRouteFirstRouteChildNestedChildRoute:
    FirstRouteFirstRouteChildNestedChildRoute,
  FirstRouteFirstRouteChildIndexRoute: FirstRouteFirstRouteChildIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
